# Generated by Django 3.0 on 2020-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lcorderemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='RC_password',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
