# Generated by Django 3.0 on 2021-04-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_rc_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='RC_username',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
