# Generated by Django 3.0 on 2020-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0003_auto_20200121_1851"),
    ]

    operations = [
        migrations.RemoveField(model_name="announcementviewmodel", name="view_time",),
        migrations.AddField(
            model_name="announcementviewmodel",
            name="view_time_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
