# Generated by Django 3.0 on 2020-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0004_auto_20200121_1852"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="body",
            field=models.TextField(default="body"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="announcement",
            name="title",
            field=models.CharField(default="title", max_length=128),
            preserve_default=False,
        ),
    ]
