# Generated by Django 3.0 on 2020-02-03 21:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0005_auto_20200124_0916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="body",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
