# Generated by Django 3.0 on 2021-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=1024)),
                ('Link', models.CharField(max_length=1024)),
                ('Icon', models.FileField(null=True, upload_to='')),
                ('BackButton', models.BooleanField(default=False)),
            ],
        ),
    ]
