# Generated by Django 3.0 on 2021-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_quicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='BackButton',
            field=models.BooleanField(default=False, verbose_name='BackButton Support'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='BackButton',
            field=models.BooleanField(default=False, verbose_name='BackButton Support'),
        ),
    ]
